### ISSUE TITLE
Please remove the "You are already logged into this account." feature

### ISSUE THREAD

**Issue by taberruu** [MRebhan/IngameAccountSwitcher#12]
The feature "You are already logged into this account." is a bit annoying when the session is invalid. 
Can you please remove it? :smile:

**Comment by taberruu** [comment]
Alternatively, add a Re-Log shortcut on the Main Menu?

**Comment by The-Fireplace** [comment]
I'll see about a way to work that out.

**Comment by The-Fireplace** [comment]
Done. Relog can be enabled/disabled in the config.
