### ISSUE TITLE
Add Keybind please

### ISSUE THREAD

**Issue by ghost** [MRebhan/IngameAccountSwitcher#14]
Can you add keybind to the mod for version 1.8.9 + since there're some mod which remove the default home screen which then make the mod button don't appear.

Thanks
Phil,

**Comment by dblsaiko** [comment]
This is the old repo (I'm no longer developing the mod), please create the issue [here](https://github.com/The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher). Also, the mod hasn't been updated in forever, so maybe you're SOL. Good luck :P
