### ISSUE TITLE
Custom Main Menu Compability

### ISSUE THREAD

**Issue by lumien231** [MRebhan/IngameAccountSwitcher#4]
Hi MRebhan,
i'm the developer of the Custom Main Menu mod which allows users to create custom menus using json files. Currently your mod is somewhat incompatible with mine since you completely replace the main menu like i do. However for your purpose i would assume that it would be sufficient to just add a button to the menu using InitGuiEvent.Post and render your text using RenderTickEvent. 

Would it be possible for you to change that?

**Comment by The-Fireplace** [comment]
I'm sure within the next few weeks we could do that. I am on vacation right now, and I believe MRebhan doesn't have his new computer set up yet. MR, comment if you are able to work on the mod right now. It will be a few days before I can do it, if you want support immediately, you fork the repo and make the changes yourself; I can merge the PR and make a build as soon as I get home.

**Comment by h1nk** [comment]
Sounds good.

**Comment by The-Fireplace** [comment]
Version 2.1.0.2 has the fix

**Comment by h1nk** [comment]
Yup, I got it in the logs, http://pastebin.com/U0JJSEuG, thanks.
